import "./globals.css";
import localFont from 'next/font/local'
import {QueryClient, QueryClientProvider} from "@tanstack/react-query";
import ReactQueryProvider from "@/components/react-query/ReactQueryProvider";

export const metadata = {
    title: 'Ease Wallet',
    description: 'Generated by Next.js',
}

const sfProReg = localFont({
    src: '../assets/fonts/SFProText-Regular.woff2',
    variable: '--font-sfProReg',
    display: 'swap'
})

const sfProMd = localFont({
    src: '../assets/fonts/SFProText-Medium.woff2',
    variable: '--font-sfProMd',
    display: 'swap'
})

const sfProSb = localFont({
    src: '../assets/fonts/SFProText-Semibold.woff2',
    variable: '--font-sfProSb',
    display: 'swap'
})

const sfProBold = localFont({
    src: '../assets/fonts/SFProText-Bold.woff2',
    variable: '--font-sfProBold',
    display: 'swap'
})

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={`${sfProReg.variable} font-sfProReg bg-[#F6F6F8]`}>
        <ReactQueryProvider>
            {children}
        </ReactQueryProvider>
        </body>
        </html>
    )
}
